version: "3.9"
services:
  ayay-db-local:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ayay
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    restart: always

volumes:
  postgres:
    name: ayay-db-local
    driver: local
